feat: initial commit of GitLab in lead toolchain
liatrio/lead-terraform pull request #417
Opened 2020-12-29 17:51 UTC by jbankes

2021-01-18 17:53 UTC, ChrisSchreiber requested changes

2021-01-18 17:53 UTC, ChrisSchreiber commented on modules/tools/gitlab/main.tf
> +  count = var.enable_gitlab ? 1 : 0
Let's move the feature flag from the resource to the parent module. This is a new feature with tf .13.

2021-01-18 17:53 UTC, ChrisSchreiber commented on stages/apps/lead/gitlab.tf
> +module "gitlab" {
Move count (feature flag) here

2021-01-18 17:53 UTC, ChrisSchreiber commented on modules/tools/gitlab/variables.tf
> +variable "enable_gitlab" {
remove feature flag from the module itself

2021-01-25 17:45 UTC, mrparkers commented on modules/tools/gitlab/gitlab-values.tpl
> +    class: toolchain-nginx
this should probably be a variable

2021-01-25 17:45 UTC, mrparkers commented on modules/tools/gitlab/gitlab-values.tpl
> +      certmanager.k8s.io/issuer: letsencrypt-dns
and this

2021-01-25 17:54 UTC, mrparkers approved these changes

2021-01-25 17:56 UTC, ChrisSchreiber approved these changes

2021-01-25 17:57 UTC, merged